name: 'タイルデプロイ'

on:
  push:
    branches:
      - main
    paths:
      - 'tileindex/**'
      - 'metadata.json'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # 差分抽出のために、全ての履歴が必要
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          # gsi-ci-tools は NodeJS v16 を必要としています
          node-version: '16'
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::204759435007:role/github-actions-tilestorage-access
          aws-region: ap-northeast-1
      - run: |
          aws s3 cp s3://gsi-test-tilebucket-ap-northeast-1/gsi-ci-tools.tgz ./gsi-ci-tools.tgz
          npm install -g ./gsi-ci-tools.tgz
      - name: Create Changefile
        env:
          BASE_SHA: ${{ github.event.before }}
        run: |
          mkdir -p data
          gsi-ci-tools create-changefile ./ ${BASE_SHA} ${GITHUB_SHA} data/change.json
          gsi-ci-tools metafile-csv-update ./ data/Metafile.csv

      - uses: actions/upload-artifact@v3
        with:
          name: changefile
          path: data/change.json

      - uses: actions/upload-artifact@v3
        with:
          name: nippo
          path: data/nippo.csv

      - name: Deploy changed files from tilestore (Oracle)
        env:
          ORACLE_OBJ_PREFIX: ${{ secrets.ORACLE_OBJ_PREFIX }}
          ORACLE_CLOUD_ACCESS_KEY_ID: ${{ secrets.ORACLE_CLOUD_ACCESS_KEY_ID }}
          ORACLE_CLOUD_SECRET_ACCESS_KEY: ${{ secrets.ORACLE_CLOUD_SECRET_ACCESS_KEY }}
        run: |
          gsi-ci-tools apply-changefile data/change.json oracleObj:${ORACLE_OBJ_PREFIX}/xyz/std/

      - name: Deploy changed files from tilestore (Backup SFTP)
        run: |
          gsi-ci-tools apply-changefile data/change.json sftp:gsi.server.go.jp/deploy/xyz/std/

      - name: Clear CDN Cache
        env:
          FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
        run: |
          gsi-ci-tools clear-fastly-cache data/change.json
