name: 'タイルCI'

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      # PNG 以外のタイルを利用する場合はこちらが不要となります。
      - name: Install dependencies
        run: |
          sudo apt-get install -y pngcheck

      - uses: actions/checkout@v3
        with:
          # 差分抽出のために、全ての履歴が必要
          # TODO: can we only fetch history this PR is interested in?
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          # gsi-ci-tools は NodeJS v16 を必要としています
          node-version: '16'
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::204759435007:role/github-actions-tilestorage-access
          aws-region: ap-northeast-1
      - run: |
          aws s3 cp s3://gsi-test-tilebucket-ap-northeast-1/gsi-ci-tools.tgz ./gsi-ci-tools.tgz
          npm install -g ./gsi-ci-tools.tgz
      - name: Create Changefile
        env:
          PR_BASE_SHA: ${{github.event.pull_request.base.sha}}
        run: |
          mkdir -p data
          gsi-ci-tools create-changefile ./ ${PR_BASE_SHA} ${GITHUB_SHA} data/change.json

      - uses: actions/upload-artifact@v3
        with:
          name: changefile
          path: data/change.json

      - uses: actions/upload-artifact@v3
        with:
          name: nippo
          path: data/nippo.csv

      - name: Retrieve changed tiles from tilestore
        run: |
          mkdir -p ./tiles
          gsi-ci-tools apply-changefile data/change.json file:./tiles

      - name: Check tiles (PNG)
        run: |
          find ./tiles -name '*.png' -print0 | xargs -0 pngcheck
